#!/system/bin/sh

# Define variables
variables() {
DT2S=$(cat /sys/android_touch/doubletap2sleep)
DT2S_TAP=$(cat /sys/android_touch/doubletap2sleep_tap)
DT2S_ACC=$(cat /sys/android_touch/doubletap2sleep_accuracy)
DT2S_TIME=$(cat /sys/android_touch/doubletap2sleep_time)

DT2S_UP=$(cat /sys/android_touch/doubletap2sleep_up)
DT2S_DOWN=$(cat /sys/android_touch/doubletap2sleep_down)
DT2S_RIGHT=$(cat /sys/android_touch/doubletap2sleep_right)
DT2S_LEFT=$(cat /sys/android_touch/doubletap2sleep_left)

DT2W=$(cat /sys/android_touch/doubletap2wake)
DT2W_TAP=$(cat /sys/android_touch/doubletap2wake_tap)
DT2W_ACC=$(cat /sys/android_touch/doubletap2wake_accuracy)
DT2W_TIME=$(cat /sys/android_touch/doubletap2wake_time)

DT2W_UP=$(cat /sys/android_touch/doubletap2wake_up)
DT2W_DOWN=$(cat /sys/android_touch/doubletap2wake_down)
DT2W_RIGHT=$(cat /sys/android_touch/doubletap2wake_right)
DT2W_LEFT=$(cat /sys/android_touch/doubletap2wake_left)

S2W=$(cat /sys/android_touch/sweep2wake)
S2S=$(cat /sys/android_touch/sweep2sleep)
S2W_INVERT=$(cat /sys/android_touch/sweep2wake_invert)

S2S_UP=$(cat /sys/android_touch/sweep2sleep_up)
S2S_DOWN=$(cat /sys/android_touch/sweep2sleep_down)
S2S_RIGHT=$(cat /sys/android_touch/sweep2sleep_right)
S2S_LEFT=$(cat /sys/android_touch/sweep2sleep_left)

S2W_UP=$(cat /sys/android_touch/sweep2wake_up)
S2W_DOWN=$(cat /sys/android_touch/sweep2wake_down)
S2W_RIGHT=$(cat /sys/android_touch/sweep2wake_right)
S2W_LEFT=$(cat /sys/android_touch/sweep2wake_left)

VIBRATE=$(cat /sys/twf_debug/vibrate)
POCKET_MOD=$(cat /sys/pocket_mod/enable)
}

# SET
DT2S_SET=$(cat /sys/android_touch/doubletap2sleep)
DT2S_TAP_SET=$(cat /sys/android_touch/doubletap2sleep_tap)
DT2S_ACC_SET=$(cat /sys/android_touch/doubletap2sleep_accuracy)
DT2S_TIME_SET=$(cat /sys/android_touch/doubletap2sleep_time)

DT2S_UP_SET=$(cat /sys/android_touch/doubletap2sleep_up)
DT2S_DOWN_SET=$(cat /sys/android_touch/doubletap2sleep_down)
DT2S_RIGHT_SET=$(cat /sys/android_touch/doubletap2sleep_right)
DT2S_LEFT_SET=$(cat /sys/android_touch/doubletap2sleep_left)

DT2W_SET=$(cat /sys/android_touch/doubletap2wake)
DT2W_TAP_SET=$(cat /sys/android_touch/doubletap2wake_tap)
DT2W_ACC_SET=$(cat /sys/android_touch/doubletap2wake_accuracy)
DT2W_TIME_SET=$(cat /sys/android_touch/doubletap2wake_time)

DT2W_UP_SET=$(cat /sys/android_touch/doubletap2wake_up)
DT2W_DOWN_SET=$(cat /sys/android_touch/doubletap2wake_down)
DT2W_RIGHT_SET=$(cat /sys/android_touch/doubletap2wake_right)
DT2W_LEFT_SET=$(cat /sys/android_touch/doubletap2wake_left)

S2W_SET=$(cat /sys/android_touch/sweep2wake)
S2S_SET=$(cat /sys/android_touch/sweep2sleep)
S2W_INVERT_SET=$(cat /sys/android_touch/sweep2wake_invert)

S2S_UP_SET=$(cat /sys/android_touch/sweep2sleep_up)
S2S_DOWN_SET=$(cat /sys/android_touch/sweep2sleep_down)
S2S_RIGHT_SET=$(cat /sys/android_touch/sweep2sleep_right)
S2S_LEFT_SET=$(cat /sys/android_touch/sweep2sleep_left)

S2W_UP_SET=$(cat /sys/android_touch/sweep2wake_up)
S2W_DOWN_SET=$(cat /sys/android_touch/sweep2wake_down)
S2W_RIGHT_SET=$(cat /sys/android_touch/sweep2wake_right)
S2W_LEFT_SET=$(cat /sys/android_touch/sweep2wake_left)

VIBRATE_SET=$(cat /sys/twf_debug/vibrate)
POCKET_MOD_SET=$(cat /sys/pocket_mod/enable)

# SYS
DT2S_SYS=/sys/android_touch/doubletap2sleep
DT2S_TAP_SYS=/sys/android_touch/doubletap2sleep_tap
DT2S_ACC_SYS=/sys/android_touch/doubletap2sleep_accuracy
DT2S_TIME_SYS=/sys/android_touch/doubletap2sleep_time

DT2S_UP_SYS=/sys/android_touch/doubletap2sleep_up
DT2S_DOWN_SYS=/sys/android_touch/doubletap2sleep_down
DT2S_RIGHT_SYS=/sys/android_touch/doubletap2sleep_right
DT2S_LEFT_SYS=/sys/android_touch/doubletap2sleep_left

DT2W_SYS=/sys/android_touch/doubletap2wake
DT2W_TAP_SYS=/sys/android_touch/doubletap2wake_tap
DT2W_ACC_SYS=/sys/android_touch/doubletap2wake_accuracy
DT2W_TIME_SYS=/sys/android_touch/doubletap2wake_time

DT2W_UP_SYS=/sys/android_touch/doubletap2wake_up
DT2W_DOWN_SYS=/sys/android_touch/doubletap2wake_down
DT2W_RIGHT_SYS=/sys/android_touch/doubletap2wake_right
DT2W_LEFT_SYS=/sys/android_touch/doubletap2wake_left

S2W_SYS=/sys/android_touch/sweep2wake
S2S_SYS=/sys/android_touch/sweep2sleep
S2W_INVERT_SYS=/sys/android_touch/sweep2wake_invert

S2S_UP_SYS=/sys/android_touch/sweep2sleep_up
S2S_DOWN_SYS=/sys/android_touch/sweep2sleep_down
S2S_RIGHT_SYS=/sys/android_touch/sweep2sleep_right
S2S_LEFT_SYS=/sys/android_touch/sweep2sleep_left

S2W_UP_SYS=/sys/android_touch/sweep2wake_up
S2W_DOWN_SYS=/sys/android_touch/sweep2wake_down
S2W_RIGHT_SYS=/sys/android_touch/sweep2wake_right
S2W_LEFT_SYS=/sys/android_touch/sweep2wake_left

VIBRATE_SYS=/sys/twf_debug/vibrate
POCKET_MOD_SYS=/sys/pocket_mod/enable

# Colour
RED='\033[0;0;31m' # Красный текст
REDB='\033[0;1;31m' # Красный текст жирный
GRN='\033[0;0;32m' # Зелёный текст
GRNB='\033[0;1;32m' # Зелёный текст жирный
YEL='\033[0;0;33m' # Жёлтый текст
YELB='\033[0;1;33m' # Жёлтый текст жирный
BLU='\033[0;0;34m' # Синий текст
BLUB='\033[0;1;34m' # Синий текст жирный
STD='\033[0;0;39m' # Стандартный текст
STDB='\033[1m' # Жирный

doubletap2sleep_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A DT2S_SET
        if ((DT2S_SET >= 0 && DT2S_SET <= 1)); then
            EXPORT DT2S_SET
            echo "$DT2S_SET" > "$DT2S_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

doubletap2sleep_tap_set() {
        clear
        menu
        echo "${YELB}Введите количество тапов [2 - 100]${STD}"
        read -A DT2S_TAP_SET
        if ((DT2S_TAP_SET >= 2 && DT2S_TAP_SET <= 100)); then
            EXPORT DT2S_TAP_SET
            echo "$DT2S_TAP_SET" > "$DT2S_TAP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [2 - 100]${STD}" && sleep 2
        fi
}

doubletap2sleep_acc_set() {
        clear
        menu
        echo "${YELB}Введите значение точности [5 - 1360] px${STD}"
        read -A DT2S_ACC_SET
        if ((DT2S_ACC_SET >= 5 && DT2S_ACC_SET <= 1360)); then
            EXPORT DT2S_ACC_SET
            echo "$DT2S_ACC_SET" > "$DT2S_ACC_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [5 - 1360]${STD}" && sleep 2
        fi
}

doubletap2sleep_time_set() {
        clear
        menu
        echo "${YELB}Введите значение времени [20 - 10000] ms${STD}"
        read -A DT2S_TIME_SET
        if ((DT2S_TIME_SET >= 20 && DT2S_TIME_SET <= 10000)); then
            EXPORT DT2S_TIME_SET
            echo "$DT2S_TIME_SET" > "$DT2S_TIME_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [20 - 10000]${STD}" && sleep 2
        fi
}

doubletap2sleep_up_set() {
        clear
        menu
        echo "${YELB}Введите значение верхней границы [0 - 1360] px${STD}"
        read -A DT2S_UP_SET
        if ((DT2S_UP_SET >= 0 && DT2S_UP_SET <= 1360)); then
            EXPORT DT2S_UP_SET
            echo "$DT2S_UP_SET" > "$DT2S_UP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1360]${STD}" && sleep 2
        fi
}

doubletap2sleep_down_set() {
        clear
        menu
        echo "${YELB}Введите значение нижней границы [0 - 1360] px${STD}"
        read -A DT2S_DOWN_SET
        if ((DT2S_DOWN_SET >= 0 && DT2S_DOWN_SET <= 1360)); then
            EXPORT DT2S_DOWN_SET
            echo "$DT2S_DOWN_SET" > "$DT2S_DOWN_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1360]${STD}" && sleep 2
        fi
}

doubletap2sleep_right_set() {
        clear
        menu
        echo "${YELB}Введите значение правой границы [0 - 720] px${STD}"
        read -A DT2S_RIGHT_SET
        if ((DT2S_RIGHT_SET >= 0 && DT2S_RIGHT_SET <= 720)); then
            EXPORT DT2S_RIGHT_SET
            echo "$DT2S_RIGHT_SET" > "$DT2S_RIGHT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

doubletap2sleep_left_set() {
        clear
        menu
        echo "${YELB}Введите значение левой границы [0 - 720] px${STD}"
        read -A DT2S_LEFT_SET
        if ((DT2S_LEFT_SET >= 0 && DT2S_LEFT_SET <= 720)); then
            EXPORT DT2S_LEFT_SET
            echo "$DT2S_LEFT_SET" > "$DT2S_LEFT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

doubletap2wake_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A DT2W_SET
        if ((DT2W_SET >= 0 && DT2W_SET <= 1)); then
            EXPORT DT2W_SET
            echo "$DT2W_SET" > "$DT2W_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

doubletap2wake_tap_set() {
        clear
        menu
        echo "${YELB}Введите количество тапов [2 - 100]${STD}"
        read -A DT2W_TAP_SET
        if ((DT2W_TAP_SET >= 2 && DT2W_TAP_SET <= 100)); then
            EXPORT DT2W_TAP_SET
            echo "$DT2W_TAP_SET" > "$DT2W_TAP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [2 - 100]${STD}" && sleep 2
        fi
}

doubletap2wake_acc_set() {
        clear
        menu
        echo "${YELB}Введите значение точности [5 - 1360] px${STD}"
        read -A DT2W_ACC_SET
        if ((DT2W_ACC_SET >= 5 && DT2W_ACC_SET <= 1360)); then
            EXPORT DT2W_ACC_SET
            echo "$DT2W_ACC_SET" > "$DT2W_ACC_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [5 - 1360]${STD}" && sleep 2
        fi
}

doubletap2wake_time_set() {
        clear
        menu
        echo "${YELB}Введите значение времени [20 - 10000] ms${STD}"
        read -A DT2W_TIME_SET
        if ((DT2W_TIME_SET >= 20 && DT2W_TIME_SET <= 10000)); then
            EXPORT DT2W_TIME_SET
            echo "$DT2W_TIME_SET" > "$DT2W_TIME_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [20 - 10000]${STD}" && sleep 2
        fi
}

doubletap2wake_up_set() {
        clear
        menu
        echo "${YELB}Введите значение верхней границы [0 - 1360] px${STD}"
        read -A DT2W_UP_SET
        if ((DT2W_UP_SET >= 0 && DT2W_UP_SET <= 1360)); then
            EXPORT DT2W_UP_SET
            echo "$DT2W_UP_SET" > "$DT2W_UP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1360]${STD}" && sleep 2
        fi
}

doubletap2wake_down_set() {
        clear
        menu
        echo "${YELB}Введите значение нижней границы [0 - 1360] px${STD}"
        read -A DT2W_DOWN_SET
        if ((DT2W_DOWN_SET >= 0 && DT2W_DOWN_SET <= 1360)); then
            EXPORT DT2W_DOWN_SET
            echo "$DT2W_DOWN_SET" > "$DT2W_DOWN_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1360]${STD}" && sleep 2
        fi
}

doubletap2wake_right_set() {
        clear
        menu
        echo "${YELB}Введите значение правой границы [0 - 720] px${STD}"
        read -A DT2W_RIGHT_SET
        if ((DT2W_RIGHT_SET >= 0 && DT2W_RIGHT_SET <= 720)); then
            EXPORT DT2W_RIGHT_SET
            echo "$DT2W_RIGHT_SET" > "$DT2W_RIGHT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

doubletap2wake_left_set() {
        clear
        menu
        echo "${YELB}Введите значение левой границы [0 - 720] px${STD}"
        read -A DT2W_LEFT_SET
        if ((DT2W_LEFT_SET >= 0 && DT2W_LEFT_SET <= 720)); then
            EXPORT DT2W_LEFT_SET
            echo "$DT2W_LEFT_SET" > "$DT2W_LEFT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

sweep2wake_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A S2W_SET
        if ((S2W_SET >= 0 && S2W_SET <= 1)); then
            EXPORT S2W_SET
            echo "$S2W_SET" > "$S2W_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

sweep2sleep_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A S2S_SET
        if ((S2S_SET >= 0 && S2S_SET <= 1)); then
            EXPORT S2S_SET
            echo "$S2S_SET" > "$S2S_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

sweep2wake_invert_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A S2W_INVERT_SET
        if ((S2W_INVERT_SET >= 0 && S2W_INVERT_SET <= 1)); then
            EXPORT S2W_INVERT_SET
            echo "$S2W_INVERT_SET" > "$S2W_INVERT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

sweep2sleep_up_set() {
        clear
        menu
        echo "${YELB}Введите значение верхнего триггера [0 - 1280] px${STD}"
        read -A S2S_UP_SET
        if ((S2S_UP_SET >= 0 && S2S_UP_SET <= 1280)); then
            EXPORT S2S_UP_SET
            echo "$S2S_UP_SET" > "$S2S_UP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1280]${STD}" && sleep 2
        fi
}

sweep2sleep_down_set() {
        clear
        menu
        echo "${YELB}Введите значение нижнего триггера [0 - 1280] px${STD}"
        read -A S2S_DOWN_SET
        if ((S2S_DOWN_SET >= 0 && S2S_DOWN_SET <= 1280)); then
            EXPORT S2S_DOWN_SET
            echo "$S2S_DOWN_SET" > "$S2S_DOWN_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1280]${STD}" && sleep 2
        fi
}

sweep2sleep_right_set() {
        clear
        menu
        echo "${YELB}Введите значение правого триггера [0 - 720] px${STD}"
        read -A S2S_RIGHT_SET
        if ((S2S_RIGHT_SET >= 0 && S2S_RIGHT_SET <= 720)); then
            EXPORT S2S_RIGHT_SET
            echo "$S2S_RIGHT_SET" > "$S2S_RIGHT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

sweep2sleep_left_set() {
        clear
        menu
        echo "${YELB}Введите значение левого триггера [0 - 720] px${STD}"
        read -A S2S_LEFT_SET
        if ((S2S_LEFT_SET >= 0 && S2S_LEFT_SET <= 720)); then
            EXPORT S2S_LEFT_SET
            echo "$S2S_LEFT_SET" > "$S2S_LEFT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

sweep2wake_up_set() {
        clear
        menu
        echo "${YELB}Введите значение верхней границы [0 - 1280] px${STD}"
        read -A S2W_UP_SET
        if ((S2W_UP_SET >= 0 && S2W_UP_SET <= 1280)); then
            EXPORT S2W_UP_SET
            echo "$S2W_UP_SET" > "$S2W_UP_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1280]${STD}" && sleep 2
        fi
}

sweep2wake_down_set() {
        clear
        menu
        echo "${YELB}Введите значение нижней границы [0 - 1280] px${STD}"
        read -A S2W_DOWN_SET
        if ((S2W_DOWN_SET >= 0 && S2W_DOWN_SET <= 1280)); then
            EXPORT S2W_DOWN_SET
            echo "$S2W_DOWN_SET" > "$S2W_DOWN_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1280]${STD}" && sleep 2
        fi
}

sweep2wake_right_set() {
        clear
        menu
        echo "${YELB}Введите значение правой границы [0 - 720] px${STD}"
        read -A S2W_RIGHT_SET
        if ((S2W_RIGHT_SET >= 0 && S2W_RIGHT_SET <= 720)); then
            EXPORT S2W_RIGHT_SET
            echo "$S2W_RIGHT_SET" > "$S2W_RIGHT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

sweep2wake_left_set() {
        clear
        menu
        echo "${YELB}Введите значение левой границы [0 - 720] px${STD}"
        read -A S2W_LEFT_SET
        if ((S2W_LEFT_SET >= 0 && S2W_LEFT_SET <= 720)); then
            EXPORT S2W_LEFT_SET
            echo "$S2W_LEFT_SET" > "$S2W_LEFT_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 720]${STD}" && sleep 2
        fi
}

haptic_feedback_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A VIBRATE_SET
        if ((VIBRATE_SET >= 0 && VIBRATE_SET <= 1)); then
            EXPORT VIBRATE_SET
            echo "$VIBRATE_SET" > "$VIBRATE_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

pocket_mod_set() {
        clear
        menu
        echo "${YELB}Введите значение [0-откл; 1-вкл]${STD}"
        read -A POCKET_MOD_SET
        if ((POCKET_MOD_SET >= 0 && POCKET_MOD_SET <= 1)); then
            EXPORT POCKET_MOD_SET
            echo "$POCKET_MOD_SET" > "$POCKET_MOD_SYS"
        else
            echo -e "${REDB}Ошибка! Значение должно быть\nв пределах [0 - 1]${STD}" && sleep 2
        fi
}

help() {
        clear
echo
echo "1)  DoubleTap2Sleep:"
echo "    Двойное нажатие для блокировки"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 0 (отключено)"
echo
echo "2)  DT2S кол-во тапов:"
echo "    Количество нажатий для блокировки"
echo "    Значения от 2 до 100"
echo "    Значение по умолчанию 2"
echo
echo "3)  DT2S точность:"
echo "    Погрешность (в пикселях). Чем меньше значение, тем точнее"
echo "    необходимо делать последующие нажатия относительного первого"
echo "    Значения от 5 до 1360"
echo "    Значение по умолчанию 50"
echo
echo "4)  DT2S время:"
echo "    Время в мсек между тапами. Чем меньше значение,"
echo "    тем быстрее нужно нажимать на экран"
echo "    Значения от 20 до 10000"
echo "    Значение по умолчанию 600"
echo
echo "5)  DT2S верхняя граница:"
echo "    Расстояние срабатывания (в пикселях) от верхней границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 0"
echo
echo "6)  DT2S нижняя граница:"
echo "    Расстояние срабатывания (в пикселях) до нижней границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 1280"
echo
echo "7)  DT2S правая граница:"
echo "    Расстояние срабатывания (в пикселях) до правой границы экрана"
echo "    Значения от 0 до 720"
echo "    Значение по умолчанию 720"
echo
echo "8)  DT2S левая граница:"
echo "    Расстояние срабатывания (в пикселях) от левой границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 0"
echo
echo "9)  DoubleTap2Wake:"
echo "    Двойное нажатие для пробуждения"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 0 (отключено)"
echo
echo "10) DT2W кол-во тапов:"
echo "    Количество нажатий для пробуждения"
echo "    Значения от 2 до 100"
echo "    Значение по умолчанию 2"
echo
echo "11) DT2W точность:"
echo "    Погрешность (в пикселях). Чем меньше значение, тем точнее"
echo "    необходимо делать последующие нажатия относительного первого"
echo "    Значения от 5 до 1360"
echo "    Значение по умолчанию 50"
echo
echo "12) DT2W время:"
echo "    Время в мсек между тапами. Чем меньше значение,"
echo "    тем быстрее нужно нажимать на экран"
echo "    Значения от 20 до 10000"
echo "    Значение по умолчанию 600"
echo
echo "13) DT2W верхняя граница:"
echo "    Расстояние срабатывания (в пикселях) от верхней границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 0"
echo
echo "14) DT2W нижняя граница:"
echo "    Расстояние срабатывания (в пикселях) до нижней границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 1280"
echo
echo "15) DT2W правая граница:"
echo "    Расстояние срабатывания (в пикселях) до правой границы экрана"
echo "    Значения от 0 до 720"
echo "    Значение по умолчанию 720"
echo
echo "16) DT2S левая граница:"
echo "    Расстояние срабатывания (в пикселях) от левой границы экрана"
echo "    Примечание: 1280 - конец экрана; 1360 - включая сенсорные кнопки"
echo "    Значения от 0 до 1360"
echo "    Значение по умолчанию 0"
echo
echo "17) Sweep2Wake:"
echo "    Провести по экрану для пробуждения"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 0 (отключено)"
echo
echo "18) Sweep2Sleep:"
echo "    Провести по экрану для блокировки"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 0 (отключено)"
echo
echo "19) S2W/S2S инверт:"
echo "    Использовать вертикальный жест"
echo "    0 - горизонтальный жест; 1 - вертикальный жест"
echo "    Значение по умолчанию 0"
echo
echo "20) S2W верхняя граница:"
echo "    Расстояние срабатывания (в пикселях) от верхней границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 240"
echo
echo "21) S2W нижняя граница:"
echo "    Расстояние срабатывания (в пикселях) до нижней границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 1270"
echo
echo "22) S2W правая граница:"
echo "    Расстояние срабатывания (в пикселях) до правой границы экрана"
echo "    Значения от 0 до 720"
echo "    Значение по умолчанию 600"
echo
echo "23) S2W левая граница:"
echo "    Расстояние срабатывания (в пикселях) от левой границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 240"
echo
echo "24) S2S верхняя граница:"
echo "    Расстояние срабатывания (в пикселях) от верхней границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 240"
echo
echo "25) S2S нижняя граница:"
echo "    Расстояние срабатывания (в пикселях) до нижней границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 1270"
echo
echo "26) S2S правая граница:"
echo "    Расстояние срабатывания (в пикселях) до правой границы экрана"
echo "    Значения от 0 до 720"
echo "    Значение по умолчанию 600"
echo
echo "27) S2S левая граница:"
echo "    Расстояние срабатывания (в пикселях) от левой границы экрана"
echo "    Значения от 0 до 1280"
echo "    Значение по умолчанию 240"
echo
echo "28) Виброотклик:"
echo "    Вибрировать при успешном распознавании жеста"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 1 (включено)"
echo
echo "29) Режим в кармане:"
echo "    Предотвращать случайное включение используя датчик приближение"
echo "    0 - отключено; 1 - включено"
echo "    Значение по умолчанию 1 (включено)"
echo
echo "30) Восстанавливает значения по умолчанию"
echo
echo "31) Применяет значения при загрузке"
echo "    (значения записываются в файл /system/etc/init.d/set)"
echo
echo "32) Эта справка"
echo
echo "33) Выход из меню"
echo
pause
}

pause() {
echo -e "${BLUB}Нажмите любую клавишу для выхода...${STD}"
read -s -n 1 -A
}

default() {
        clear
        menu
echo "0" > "$DT2S_SYS"
echo "2" > "$DT2S_TAP_SYS"
echo "50" > "$DT2S_ACC_SYS"
echo "600" > "$DT2S_TIME_SYS"

echo "0" > "$DT2S_UP_SYS"
echo "1280" > "$DT2S_DOWN_SYS"
echo "720" > "$DT2S_RIGHT_SYS"
echo "0" > "$DT2S_LEFT_SYS"

echo "0" > "$DT2W_SYS"
echo "2" > "$DT2W_TAP_SYS"
echo "50" > "$DT2W_ACC_SYS"
echo "600" > "$DT2W_TIME_SYS"

echo "0" > "$DT2W_UP_SYS"
echo "1280" > "$DT2W_DOWN_SYS"
echo "720" > "$DT2W_RIGHT_SYS"
echo "0" > "$DT2W_LEFT_SYS"

echo "0" > "$S2W_SYS"
echo "0" > "$S2S_SYS"
echo "0" > "$S2W_INVERT_SYS"

echo "800" > "$S2W_UP_SYS"
echo "1260" > "$S2W_DOWN_SYS"
echo "600" > "$S2W_RIGHT_SYS"
echo "240" > "$S2W_LEFT_SYS"

echo "800" > "$S2S_UP_SYS"
echo "1260" > "$S2S_DOWN_SYS"
echo "600" > "$S2S_RIGHT_SYS"
echo "240" > "$S2S_LEFT_SYS"

echo "1" > "$VIBRATE_SYS"
echo "1" > "$POCKET_MOD_SYS"

DT2S_SET=0
DT2S_TAP_SET=2
DT2S_ACC_SET=50
DT2S_TIME_SET=600

DT2S_UP_SET=0
DT2S_DOWN_SET=1280
DT2S_RIGHT_SET=720
DT2S_LEFT_SET=0

DT2W_SET=0
DT2W_TAP_SET=2
DT2W_ACC_SET=50
DT2W_TIME_SET=600

DT2W_UP_SET=0
DT2W_DOWN_SET=1280
DT2W_RIGHT_SET=720
DT2W_LEFT_SET=0

S2W_SET=0
S2S_SET=0
S2W_INVERT_SET=0

S2W_UP_SET=800
S2W_DOWN_SET=1260
S2W_RIGHT_SET=600
S2W_LEFT_SET=240

S2S_UP_SET=800
S2S_DOWN_SET=1260
S2S_RIGHT_SET=600
S2S_LEFT_SET=240

VIBRATE_SET=1
POCKET_MOD_SET=1

echo -e "${BLUB}Значения по умолчанию восстановлены${STD}" && sleep 2
}

write_script() {
        clear
        menu
        mount -o remount,rw /system
	rm -rf /system/etc/init.d/set
(cat << EOF) > /system/etc/init.d/set
#!/system/bin/sh

echo "${DT2S_SET}" > "${DT2S_SYS}"
echo "${DT2S_TAP_SET}" > "${DT2S_TAP_SYS}"
echo "${DT2S_ACC_SET}" > "${DT2S_ACC_SYS}"
echo "${DT2S_TIME_SET}" > "${DT2S_TIME_SYS}"

echo "${DT2S_UP_SET}" > "${DT2S_UP_SYS}"
echo "${DT2S_DOWN_SET}" > "${DT2S_DOWN_SYS}"
echo "${DT2S_RIGHT_SET}" > "${DT2S_RIGHT_SYS}"
echo "${DT2S_LEFT_SET}" > "${DT2S_LEFT_SYS}"

echo "${DT2W_SET}" > "${DT2W_SYS}"
echo "${DT2W_TAP_SET}" > "${DT2W_TAP_SYS}"
echo "${DT2W_ACC_SET}" > "${DT2W_ACC_SYS}"
echo "${DT2W_TIME_SET}" > "${DT2W_TIME_SYS}"

echo "${DT2W_UP_SET}" > "${DT2W_UP_SYS}"
echo "${DT2W_DOWN_SET}" > "${DT2W_DOWN_SYS}"
echo "${DT2W_RIGHT_SET}" > "${DT2W_RIGHT_SYS}"
echo "${DT2W_LEFT_SET}" > "${DT2W_LEFT_SYS}"

echo "${S2W_SET}" > "${S2W_SYS}"
echo "${S2S_SET}" > "${S2S_SYS}"
echo "${S2W_INVERT_SET}" > "${S2W_INVERT_SYS}"

echo "${S2W_UP_SET}" > "${S2W_UP_SYS}"
echo "${S2W_DOWN_SET}" > "${S2W_DOWN_SYS}"
echo "${S2W_RIGHT_SET}" > "${S2W_RIGHT_SYS}"
echo "${S2W_LEFT_SET}" > "${S2W_LEFT_SYS}"

echo "${S2S_SET}" > "${S2S_SYS}"
echo "${S2S_UP_SET}" > "${S2S_UP_SYS}"
echo "${S2S_DOWN_SET}" > "${S2S_DOWN_SYS}"
echo "${S2S_RIGHT_SET}" > "${S2S_RIGHT_SYS}"
echo "${S2S_LEFT_SET}" > "${S2S_LEFT_SYS}"

echo "${VIBRATE_SET}" > "${VIBRATE_SYS}"
echo "${POCKET_MOD_SET}" > "${POCKET_MOD_SYS}"
EOF
        chmod 755 /system/etc/init.d/set
        mount -o remount,ro /system
        echo -e "${BLUB}Значения при загрузке установлены${STD}" && sleep 2
}

menu() {
        clear
        echo
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}1. DoubleTap2Sleep: ${YELB}"$DT2S"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}2. DT2S кол-во тапов: ${YELB}"$DT2S_TAP"${STD}"
        echo -e "${GRNB}3. DT2S точность: ${YELB}"$DT2S_ACC"${STD}"
        echo -e "${GRNB}4. DT2S время: ${YELB}"$DT2S_TIME"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}5. DT2S верхняя граница: ${YELB}"$DT2S_UP"${STD}"
        echo -e "${GRNB}6. DT2S нижняя граница: ${YELB}"$DT2S_DOWN"${STD}"
        echo -e "${GRNB}7. DT2S правая граница: ${YELB}"$DT2S_RIGHT"${STD}"
        echo -e "${GRNB}8. DT2S левая граница: ${YELB}"$DT2S_LEFT"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}9. DoubleTap2Wake: ${YELB}"$DT2W"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}10. DT2SW кол-во тапов: ${YELB}"$DT2W_TAP"${STD}"
        echo -e "${GRNB}11. DT2W точность: ${YELB}"$DT2W_ACC"${STD}"
        echo -e "${GRNB}12. DT2W время: ${YELB}"$DT2W_TIME"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}13. DT2W верхняя граница: ${YELB}"$DT2W_UP"${STD}"
        echo -e "${GRNB}14. DT2W нижняя граница: ${YELB}"$DT2W_DOWN"${STD}"
        echo -e "${GRNB}15. DT2W правая граница: ${YELB}"$DT2W_RIGHT"${STD}"
        echo -e "${GRNB}16. DT2W левая граница: ${YELB}"$DT2W_LEFT"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}17. Sweep2Wake: ${YELB}"$S2W"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}18. Sweep2Sleep: ${YELB}"$S2S"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}19. S2W/S2S инверт: ${YELB}"$S2W_INVERT"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}20. S2W верхняя граница: ${YELB}"$S2W_UP"${STD}"
        echo -e "${GRNB}21. S2W нижняя граница: ${YELB}"$S2W_DOWN"${STD}"
        echo -e "${GRNB}22. S2W правая граница: ${YELB}"$S2W_RIGHT"${STD}"
        echo -e "${GRNB}23. S2W левая граница: ${YELB}"$S2W_LEFT"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}24. S2S верхняя граница: ${YELB}"$S2S_UP"${STD}"
        echo -e "${GRNB}25. S2S нижняя граница: ${YELB}"$S2S_DOWN"${STD}" 
        echo -e "${GRNB}26. S2S правая граница: ${YELB}"$S2S_RIGHT"${STD}"
        echo -e "${GRNB}27. S2S левая граница: ${YELB}"$S2S_LEFT"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}28. Виброотклик: ${YELB}"$VIBRATE"${STD}"
        echo -e "${GRNB}29. Режим в кармане: ${YELB}"$POCKET_MOD"${STD}"
        echo -e "${BLUB}*****************************${STD}"
        echo -e "${GRNB}30. Восстановить значения по умолчанию${STD}"
        echo -e "${GRNB}31. Применить при загрузке${STD}"
        echo -e "${GRNB}32. Справка${STD}"
        echo -e "${GRNB}33. Выход${STD}"
        echo -e "${BLUB}*****************************${STD}"
}

read_options() {
        echo -e "${YELB}Введите номер пункта [1 - 33]${STD}"
        local choice
        read -A choice
        case $choice in
            1) doubletap2sleep_set ;;
            2) doubletap2sleep_tap_set ;;
            3) doubletap2sleep_acc_set ;;
            4) doubletap2sleep_time_set ;;
            5) doubletap2sleep_up_set ;;
            6) doubletap2sleep_down_set ;;
            7) doubletap2sleep_right_set ;;
            8) doubletap2sleep_left_set ;;
            9) doubletap2wake_set ;;
            10) doubletap2wake_tap_set ;;
            11) doubletap2wake_acc_set ;;
            12) doubletap2wake_time_set ;;
            13) doubletap2wake_up_set ;;
            14) doubletap2wake_down_set ;;
            15) doubletap2wake_right_set ;;
            16) doubletap2wake_left_set ;;
            17) sweep2wake_set ;;
            18) sweep2sleep_set ;;
            19) sweep2wake_invert_set ;;
            20) sweep2wake_up_set ;;
            21) sweep2wake_down_set ;;
            22) sweep2wake_right_set ;;
            23) sweep2wake_left_set ;;
            24) sweep2sleep_up_set ;;
            25) sweep2sleep_down_set ;;
            26) sweep2sleep_right_set ;;
            27) sweep2sleep_left_set ;;
            28) haptic_feedback_set ;;
            29) pocket_mod_set ;;
            30) default ;;
            31) write_script ;;
            32) help ;;
            33) clear
                exit 0 ;;
            *)  echo -e "${REDB}Ошибка! Неверный номер пункта${STD}" && sleep 2
        esac
}

(while true; do
        variables
        menu
        read_options
done)
